// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: protos/v1/course.proto

package course

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Teste       string `protobuf:"bytes,3,opt,name=teste,proto3" json:"teste,omitempty"`
}

func (x *CourseMessage) Reset() {
	*x = CourseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_v1_course_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseMessage) ProtoMessage() {}

func (x *CourseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_v1_course_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseMessage.ProtoReflect.Descriptor instead.
func (*CourseMessage) Descriptor() ([]byte, []int) {
	return file_protos_v1_course_proto_rawDescGZIP(), []int{0}
}

func (x *CourseMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CourseMessage) GetTeste() string {
	if x != nil {
		return x.Teste
	}
	return ""
}

var File_protos_v1_course_proto protoreflect.FileDescriptor

var file_protos_v1_course_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x22, 0x57, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_v1_course_proto_rawDescOnce sync.Once
	file_protos_v1_course_proto_rawDescData = file_protos_v1_course_proto_rawDesc
)

func file_protos_v1_course_proto_rawDescGZIP() []byte {
	file_protos_v1_course_proto_rawDescOnce.Do(func() {
		file_protos_v1_course_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_v1_course_proto_rawDescData)
	})
	return file_protos_v1_course_proto_rawDescData
}

var file_protos_v1_course_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_v1_course_proto_goTypes = []interface{}{
	(*CourseMessage)(nil), // 0: course.CourseMessage
}
var file_protos_v1_course_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_v1_course_proto_init() }
func file_protos_v1_course_proto_init() {
	if File_protos_v1_course_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_v1_course_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_v1_course_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_v1_course_proto_goTypes,
		DependencyIndexes: file_protos_v1_course_proto_depIdxs,
		MessageInfos:      file_protos_v1_course_proto_msgTypes,
	}.Build()
	File_protos_v1_course_proto = out.File
	file_protos_v1_course_proto_rawDesc = nil
	file_protos_v1_course_proto_goTypes = nil
	file_protos_v1_course_proto_depIdxs = nil
}
